name: Herobrine
main: com.nkrecklow.herobrine.Herobrine
author: steaks4uce
version: 2.1
description: Hes watching... and waiting.
commands:
  hb:
    description: Various action commands
    usage: /hb