name: Herobrine
main: com.nkrecklow.herobrine.Main
author: steaks4uce
version: 4.7
description: He is watching... and waiting.
commands:
  hb:
    description: Herobrine commands.
    usage: /hb
permissions:
  herobine.commands:
    description: Gives user access to Herobrine's commands.
  herobrine.ignore:
    description: Stops Herobrine from targetting the player.